# Generated by Django 4.2.3 on 2023-08-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('NickName', models.CharField(max_length=50)),
                ('Age', models.PositiveSmallIntegerField()),
                ('Is_Activate', models.BooleanField(default=True)),
            ],
        ),
    ]
